# Generated by Django 2.1 on 2021-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('twitterId', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('username', models.CharField(max_length=255)),
                ('followers_count', models.IntegerField()),
                ('lang', models.CharField(max_length=255)),
                ('tweet', models.TextField()),
                ('retweet_count', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
